### ISSUE TITLE
Respected Sir VedAstro Module is not installing in Python 3.12.2 Version

### ISSUE THREAD

**Issue by raj2024-05** [VedAstro/VedAstro.Python#13]
My os Windows 11, Python 3.12.2 Verson

Sir when i am traing to install VedAstro using with this command    "pip install VedAstro" it is showing this below error. Please help to install VedAstro

ERROR: Ignored the following versions that require a different python version: 0.1b0 Requires-Python >=3.9,<3.12; 0.2 Requires-Python >=3.9,<3.12; 0.2b0 Requires-Python >=3.9,<3.12; 0.3.0 Requires-Python >=3.9,<3.12; 0.4.0 Requires-Python >=3.9,<3.12; 0.5.0 Requires-Python >=3.9,<3.12; 1.0.0 Requires-Python >=3.9,<3.12; 1.1.0 Requires-Python >=3.9,<3.12; 1.1.1 Requires-Python >=3.9,<3.12; 1.1.2 Requires-Python >=3.9,<3.12; 1.1.3 Requires-Python >=3.9,<3.12; 1.1.4 Requires-Python >=3.9,<3.12; 1.1.5 Requires-Python >=3.9,<3.12; 1.1.6 Requires-Python >=3.9,<3.12; 1.1.7 Requires-Python >=3.9,<3.12; 1.10.0 Requires-Python >=3.9,<3.12; 1.11.0 Requires-Python >=3.9,<3.12; 1.12.0 Requires-Python >=3.9,<3.12; 1.13.0 Requires-Python >=3.9,<3.12; 1.14.0 Requires-Python >=3.9,<3.12; 1.15.0 Requires-Python >=3.9,<3.12; 1.16.0 Requires-Python >=3.9,<3.12; 1.17.0 Requires-Python >=3.9,<3.12; 1.18.0 Requires-Python >=3.9,<3.12; 1.19.0 Requires-Python >=3.9,<3.12; 1.2.0 Requires-Python >=3.9,<3.12; 1.20.0 Requires-Python >=3.9,<3.12; 1.21.0 Requires-Python >=3.9,<3.12; 1.3.0 Requires-Python >=3.9,<3.12; 1.4.0 Requires-Python >=3.9,<3.12; 1.5.0 Requires-Python >=3.9,<3.12; 1.6.0 Requires-Python >=3.9,<3.12; 1.7.0 Requires-Python >=3.9,<3.12; 1.8.0 Requires-Python >=3.9,<3.12; 1.9.0 Requires-Python >=3.9,<3.12
ERROR: Could not find a version that satisfies the requirement VedAstro (from versions: none)
ERROR: No matching distribution found for VedAstro

**Comment by sengiv** [comment]
Very simple problem, use small caps
`pip install vedastro`

**Comment by TharakaUmayanga** [comment]
@sengiv   I think the problem is with this line in  pyproject.toml
```python
python = ">=3.9,<3.12"
``` 

which I updated to 

```python
python = ">=3.9,<3.13"

``` 
@raj2024-05  please reinstall in a new virtual environment and let us know whether the issue fixed

**Comment by sengiv** [comment]
@TharakaUmayanga nice catch 👌

**Comment by raj2024-05** [comment]
Thanks sir for your feedback.
 now i installed 
Thanks for all
