### ISSUE TITLE
Capricorn is the correct name of the zodiac

### ISSUE THREAD

**Issue by kiranramanna** [VedAstro/VedAstro.Python#9]
https://github.com/VedAstro/VedAstro.Python/blob/7b2010363b1441f741156299fcf95577650aeab1/vedastro/objects/zodiacname.py#L14

Capricornus usually refers to the constellation, and Capricorn usually refers to the astrological (zodiac) sign. Hence this has to be changed to Capricorn.

**Comment by sengiv** [comment]
Very nice catch 👌 
Will correct it soon.
If I'm not mistaken it was copied from "Manual of Astrology", but it's obviously a mistake.
Never seen anyone else say "Capricornus"

**Comment by sengiv** [comment]
fixed 😁
